version: '2'
services:
    sakini-app:
        image: sakini
        external_links:
            - sakini-mysql:mysql
            - sakini-elasticsearch:elasticsearch
            - kafka:kafka
            - zookeeper:zookeeper
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sakini?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK-NODES=zookeeper
        ports:
            - 8080:8080
    sakini-mysql:
        extends:
            file: mysql.yml
            service: sakini-mysql
    sakini-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: sakini-elasticsearch
    kafka:
        extends:
            file: kafka.yml
            service: kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
